### PR TITLE
fix: add parameters as optional

### PR DESCRIPTION
**Pull request by barbmarcio**

### CODE REVIEW

**Comment by PabloReszczynski** [comment]
Shouldn't we replace the events types with the ones from the sdk?

**Comment by jbergstroem** [comment]
Nitpick but please sort attributes a-z

**Comment by barbmarcio** [comment]
> Shouldn't we replace the events types with the ones from the sdk?

These are from the original analytics, but modified to what we expect for optional / required fields

**Comment by jbergstroem** [comment]
Can we land this?

**Review by jbergstroem — APPROVED** [review]

**Pull request merged**
